
# Setting this to true will cause armored elytras to be unbreakable.
unbreakable: false

# Amount of items it takes to fully repair an armored elytra
# Repair cost for every tier of armored elytra in number of items to repair 100%.
leatherRepair: 6
goldRepair: 5
ironRepair: 4
diamondsRepair: 3

# Name colors for every tier.
leatherColor:
goldColor:
chainColor:
ironColor:
diamondColor:

# Name for every tier:
leather:
gold: 
chain: 
iron: 
diamond: 


# Will curses (vanishing, binding) be transferred when creating armored elytras?
allowCurses: true

# List of enchantments that are allowed to be put on an armored elytra.
# If you do not want to allow any enchantments, remove them all and add "NONE"
# You can find supported enchantments here:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
allowedEnchantments:
#  - NONE
  - DURABILITY
  - PROTECTION_FIRE
  - PROTECTION_EXPLOSIONS
  - PROTECTION_PROJECTILE
  - PROTECTION_ENVIRONMENTAL
  - THORNS
  
# Message players receive when they lack the required permissions to wear a certain armor tier. "NONE" = no message. 
# %ARMOR_TIER% is replaced by the name of the armor tier.
usageDeniedMessage: 'You do not have the required permissions to wear %ARMOR_TIER% armored elytras!'

# Message players receive when they are given an armored elytra using commands. "NONE" = no message. 
# %ARMOR_TIER% is replaced by the name of the armor tier.
elytraReceivedMessage: '&2A(n) %ARMOR_TIER% armored elytra has been bestowed upon you!'

# The name of armored elytras. %ARMOR_TIER% is replaced by the name of the armor tier.
elytraName: '%ARMOR_TIER% Armored Elytra'

# The lore of armored elytras. "NONE" = no lore. %ARMOR_TIER% is replaced by the name of the armor tier.
elytraLore: 'Elytra with %ARMOR_TIER% level protection'

# Allow this plugin to check for updates on startup. It will not download new versions!
checkForUpdates: true

# Allow this plugin to send (anonymised) stats using bStats.
allowStats: true

# Setting this to true will disable this plugin and remove any armored elytras it can find.
# It will check player's inventories and their end chest upon login and any regular chest when it is opened.
# This means it will take a while for all armored elytras to be removed from your server, but it doesn't take up 
# a lot of resources, so you can just leave it installed and ignore it.
uninstall: false