# Amount of items it takes to fully repair an armored elytra
# Repair cost for every tier of armored elytra in number of items to repair 100%.
leatherRepair: 6
goldRepair: 5
ironRepair: 4
diamondsRepair: 3

# Will curses (vanishing, binding) be transferred when creating armored elytras?
allowCurses: true

# List of enchantments that are allowed to be put on an armored elytra.
# If you do not want to allow any enchantments, remove them all and add "NONE"
allowedEnchantments:
#  - NONE
  - DURABILITY
  - PROTECTION_FIRE
  - PROTECTION_EXPLOSIONS
  - PROTECTION_PROJECTILE
  - PROTECTION_ENVIRONMENTAL
  - THORNS
  
# Message players receive when they lack the required permissions to wear a certain armor tier. "NONE" = no message
usageDeniedMessage: "You do not have the required permissions to wear %ARMOR_TIER% armored elytras!"

# Message players receive when they are given an armored elytra using commands. "NONE" = no message
elytraReceivedMessage: "A(n) %ARMOR_TIER% armored elytra has been bestowed upon you!"

# Allow this plugin to check for updates on startup. It will not download new versions!
checkForUpdates: true